### PR TITLE
Scan Inverted QR Code

### PR DESCRIPTION
**Pull request by manijshrestha**
There has been a lot of requests to be able to scan inverted QR code. 
https://github.com/zxing/zxing/issues/194

This change allows to scan inverted QR Code

### CODE REVIEW

**Comment by manijshrestha** [comment]
Thanks @dm77

**Comment by dm77** [comment]
@manijshrestha Sure. Thank you for the PR. I unfortunately can't get it to scan inverted qr codes on either Nexus 5 or Google Pixel. Were you able to scan any inverted qr codes with your fix?

**Comment by manijshrestha** [comment]
Yes I was, I tested this on Pixel, Nexus 6p, 5X Sammy S6, S7 and couple more.

**Comment by dm77** [comment]
Ok thank you so much for confirming. Seems like I need to refresh Android studio, trying again..

**Comment by dm77** [comment]
Oops forgot this in build.gradle compile project(":zxing"). Works great now. Thank you

**Comment by dm77** [comment]
Ok this is now merged in v1.9.1. Thank you again.

**Pull request merged**
