### PR TITLE
making API for ZXingScannerView for UI customisation

### PR DESCRIPTION
**Pull request by marchelo**
with this pull request i'm trying to make ZXingScannerView UI customizable. 
It can be done by proving custom ViewFinderView with its own UI.

### CODE REVIEW

**Comment by marchelo** [comment]
added 2 more commits, 
not sure in 3rd one, 
but i think 2nd is very useful

**Comment by deepdoradla** [comment]
Hi Marchelo,

Great work. Is this pull request merged?

Also can you please give an example on how we customise the scanner UI ?

**Comment by marchelo** [comment]
Hello, deepdoradla. Thanks for your response.
No, this pull request is not yet merged.
If it will be merged, we will have an ability to customize scanner UI in 3 main ways:
1) changing simply colors of current UI (the most simple one)
```  
        mScannerView = new ZXingScannerView(this) {
            @Override
            protected IViewFinder createViewFinderView(Context context) {
                ViewFinderView finderView = new ViewFinderView(context);
                finderView.setLaserColor(Color.GREEN);
                finderView.setMaskColor(Color.RED);
                return finderView ;
            }
        };
        setContentView(mScannerView);
```

2) Extending `ViewFinderView` and overriding drawing methods etc.
```  
    @Override
    public void onCreate(Bundle state) {
        super.onCreate(state); 
        mScannerView = new ZXingScannerView(this) {
            @Override
            protected IViewFinder createViewFinderView(Context context) {
                return new CustomViewFinderView(context);
            }
        };
        setContentView(mScannerView);
    }
    ...
    private static class CustomViewFinderView extends ViewFinderView {
        ...
        @Override
        public void onDraw(Canvas canvas) {
            //drawViewFinderMask(canvas);               //avoiding drawing finder mask
            drawViewFinderBorder(canvas);
            //drawLaser(canvas);                                 //avoiding drawing laser
            drawTradeMark(canvas);                           //drawing for example trademark
        }
        private void drawTradeMark(Canvas canvas) {
             ... // trade mark drawing implementation here
        }
    }
```
3) Writing own view or layout by extending `android.view.View` or `android.view.ViewGroup` or other view and implementing interface methods `me.dm7.barcodescanner.core.IViewFinder` (the most complex one)
```  
    @Override
    public void onCreate(Bundle state) {
        super.onCreate(state); 
        mScannerView = new ZXingScannerView(this) {
            @Override
            protected IViewFinder createViewFinderView(Context context) {
                return new CustomViewFinderView(context);
            }
        };
        setContentView(mScannerView);
    }
    ...
    private static class CustomViewFinderView extends View implements IViewFinder {
        //view implementation here
    }
```
in this way you can write any UI you want, including making complex layouts with buttons, some bars etc.

**Comment by dm77** [comment]
@marchelo Thank you so so much for the PR and I am so sorry for not replying sooner. Please give me till the weekend to review this commit and merge it in. Thanks for your patience.

**Comment by bvanhou** [comment]
This is great! Exactly what I need :) If I am understanding this @marchelo you can add overlays on the Camera Preview right? I am looking to animate an overlay layout after a scan result is received.

**Comment by marchelo** [comment]
Thanks, @bvanhou. If I understood you right, you are right :) With this feature you will be able to draw anything or add another view above camera preview, orienting on 'scanning rectangle' (for ex. draw smth. below 'scanning rectangle' or place text view with info to right of scanning 'scanning rectangle').

**Comment by hslls** [comment]
@dm77 when will have a new release include this feature?

**Comment by deepdoradla** [comment]
Thanks so much for your response @marchelo.

Has this pull request been merged yet?

**Comment by naorcho** [comment]
Hi Marchelo,

How can I get your code?
I have tried to to put  compile 'me.dm7.barcodescanner:zxing:1.7.2'
in the Grandle and also compile 'me.dm7.zbar:1.7.2'

but it can't find IViewFinder.

How can I compile your branch ?

**Comment by marchelo** [comment]
Hi @deepdoradla, no, not yet merged.
Hi @naorcho, I don't know how to checkout to my pull-request, but anyway you can check this code by cloning https://github.com/marchelo/barcodescanner.git . And to be able to build my pull-request you should build :core module, cause my changes was made also there.
So steps will be next(1 way):
1) build :core module
2) build :zxing:zxing module

or (2 way, better)
1) change build.gradle in :zxing module
from 
```
dependencies {
//    compile project(":core")
    compile 'me.dm7.barcodescanner:core:1.7'
```
to 
```
dependencies {
    compile project(":core")
//    compile 'me.dm7.barcodescanner:core:1.7'
```
2) build :zxing:zxing module

**Comment by naorcho** [comment]
Thank you so much, I'll try it

**Comment by marchelo** [comment]
>Thank you so much, I'll try it.
>BTW, will it work on ZBar as well?

I haven't check, but I think it will

**Comment by naorcho** [comment]
I manage to use Zxing as a mudule.
but when trying to change the build.grandle of zxing to use the local 'core' folder i get:

Error:(12, 0) Could not find property 'supportLibraryDependency' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@4e45c45.

do you know why?

**Comment by naorcho** [comment]
Manage to fix it by removing: compile supportLibraryDependency
from the Core's grandle file

**Comment by termi123** [comment]
@marchelo Thank you so so much, but i want only change border and laser in 0.5s only when detect barcode, how can i do that ?

**Comment by igordelorenzi** [comment]
@dm77, any new previsions about merging this PR?

**Comment by marchelo** [comment]
Hello @termi123, thanks for your comment, but I think there is no sense to discuss this API usage while it is not merged yet.
@dm77 , please, merge it or close if it's unsuitable to avoid indeterminacy.

**Comment by luiseduardobrito** [comment]
waiting for merge!

**Comment by dm77** [comment]
@marchelo Sorry I have no excuses for the delay other than being extremely busy with work :(. Thanks so much for the pull request and sorry everyone for the delay.

**Comment by dm77** [comment]
I will push update to maven later tonight.

**Comment by deepdoradla** [comment]
Hi @marchelo I am trying to add the custom view based on the example you have provided above. I have copied it to below for reference.
    
    private static class CustomViewFinderView extends View implements IViewFinder {
        //view implementation here
    }

I am a beginner to intermediate android developer. I need to add a button, could you please explain how I can add a custom view inside CustomViewFinderView ?

Greatly appreciate your time and help.

**Comment by marchelo** [comment]
I think there are 2 ways to do that(depending on what exactly do you need)
1) easy:
```  
       <RelativeLayout
            android:width="..."
            android:height="..."
            .... >
           <ZXingScannerView
            android:width="match_parent"
            android:height="match_parent" />
          
          <Button
            android:width="wrap_content"
            android:height="wrap_content" 
            ...
            android:alignParentBottom="true"/>

         </RelativeLayout>
```
2) complex but more powerful(you will be able to orient Button depending on a view finder rectangle coordinates)
try this:
```  
    @Override
    public void onCreate(Bundle state) {
        super.onCreate(state); 
        mScannerView = new ZXingScannerView(this) {
            @Override
            protected IViewFinder createViewFinderView(Context context) {
                return new CustomViewFinderView(context);
            }
        };
        setContentView(mScannerView);
    }
    ...
    private static class CustomViewFinderView extends ViewGroup implements IViewFinder {
         //view implementation here

         Button myButton;
         public CustomViewFinderView(Context context) {
             this(context, null);
             myButton = new Button(context);
             addView(myButton);
          }

         @Override
         protected void onLayout(boolean changed, int l, int t, int r, int b) {
           Rect frameRect = getFramingRect();
           myButton.layout(frameRect.left, frameRect.bottom + 20, frameRect.left + myButton.getMeasuredWidth(), frameRect.bottom + 20 + myButton.getMeasuredHeight());
         }
    } 
```
all methods needed to implement IViewFinder interface you may copy from ViewFinderView

**Comment by pdebonte** [comment]
How about extending README.md with some of @marchelo's examples:
https://github.com/dm77/barcodescanner/pull/80#issuecomment-100556779

**Comment by chitrey** [comment]
hi @marchelo, 
I am really new to android. I would like to apologize before asking my question, i am certain this ques had been asked before but i still am stuck on it. How am I to scale the scanner View and also remove the borders? Is there any way of achieving this? Any help or guidance would be really grateful. Once again i am sorry to bother you. Thank you in advance

**Comment by 0xSeven** [comment]
Hey @marchelo,
I 'm also trying to add a custom XML layout to the scanner.
Your answer, however, seems outdated. 

Could someone please tell us how to add custom views? 
The second approach is way too complex for me currently.

**Comment by sahityaPasnoor** [comment]
Anyone looking for resizing the scanner view to match enclosing view, here is the snippet.
Scanner view will take entire dimension of enclosing view.

`private static class ResizableViewFinder extends ViewFinderView {
        public ResizableViewFinder(Context context) {
            super(context);
        }

        public ResizableViewFinder(Context context, AttributeSet attributeSet) {
            super(context, attributeSet);
        }

        @Override
        public void onDraw(Canvas canvas) {
            drawViewFinderBorder(canvas);
            drawViewFinderMask(canvas);
            drawLaser(canvas);
            drawViewFinderBorder(canvas);

        }

        @Override
        public Rect getFramingRect() {
            final Rect rect = new Rect();
         //scannerHolder is the linear layout to hold "ZXingScannerView" in the view layout.
            scannerHolder.getDrawingRect(rect);
            return rect;
        }
    }`

`
//scannerHolder is the linear layout to hold "ZXingScannerView" in the view layout.
 scannerHolder = findViewById(R.id.qr_scanner_view_holder);
mScannerView = new ZXingScannerView(this) {
            @Override
            protected IViewFinder createViewFinderView(Context context) {
                return new ResizableViewFinder(context);
            }
        };
        mScannerView.setBorderStrokeWidth(30);
        scannerHolder.addView(mScannerView);`

**Pull request merged**
