### PR TITLE
Graphical customazation + fix drawing issue

### PR DESCRIPTION
**Pull request by albinpoignot**
Technical point of view :
* Add attrs to be used in BarcodeScannerView
* Pass the new attrs to ViewFinderView
* Fix drawing lines issues (small offset on each corners due to the way `Paint` works)

Functionnal point of view : 
* Add graphical customization from the XML inflation of BarcodeScannerView
* Fix corners drawing issue (small offset on each corner)

### CODE REVIEW

**Comment by dm77** [comment]
Ah this is a good one. Has been on list of todos for 2.0 release that I have been holding back for a while now. Will merge this in with my changes. Thank you for this.

**Comment by albinpoignot** [comment]
I just used Path instead of drawLine. It's a simpler way and also it allows me to make rounded corners. You could wait a little longer before merging if you want too :)

**Comment by albinpoignot** [comment]
Can one of the admin review this patch ?

**Comment by dm77** [comment]
@albinpoignot This is now available in v1.9.3. Thank you so much:
a.) for waiting on me for 2 months to merge this commit
b.) for adding this very useful customization feature

Sorry for any trouble I caused you

**Pull request merged**
