### PR TITLE
Allow camera preview to stretch to fill available space

### LINKED ISSUE #121: preview area in landscape not getting full screen
Hi,

Surely, this is not an issue, but a lack of documentation....

If I rotate the device in landscape mode, the preview area will not expand to full screen, but preserves the ratio of the portrait mode.

How can I adjust (or config) it?

### PR DESCRIPTION
**Pull request by Rking788**
The default behavior is to continue scaling the camera preview to maintain the optimal aspect ratio. This looks better and should be used for all apps that have a  fullscreen scanner view. There are some cases where it is desired to just have the scanner view use the entire area instead of having large blank space on either side. There are optional constructors and XML layout attributes to force the camera preview to use the entire container space. The two scanner view constructors are:

`public ZBarScannerView(Context context, boolean stretchCameraToFill)`
`public ZXingScannerView(Context context, boolean stretchCameraToFill)`

to use the XML layout attributes add the following namespace to the root layout:

`xmlns:scanner="http://schemas.android.com/apk/res-auto"`

and add this attribute to the scanner view:

`scanner:stretchCameraToFill="true"`

To test these changes, the build.grade files will need to be changed to build the local projects instead of version 1.8.3 used by Maven. The SimpleScannerFragmentActivity can then be changed to use the `activity_scanner_fragment_with_headerfooter.xml` layout file. Then change the second parameter in the ZxingScannerView constructor to true to see the stretched appearance and false to see the default behavior of scaling the camera preview. See the screenshots attached.

stretch-false
stretch-true

Fixes #121, #118

### CODE REVIEW

**Comment by dm77** [comment]
Hi @Rking788 Thanks for submitting this pull request. Actually older versions of the library behaved like your request. However stretching the camera preview will cause the scanning to work incorrectly. 

For example see my comment in #8 . A fix is in #67

**Comment by dm77** [comment]
Please let me know if my assumption is incorrect.

**Comment by Rking788** [comment]
When I was doing some testing the scanning still seemed to work alright for UPC codes but I can see it being a problem with QR codes. It would still be nice to be able to use the barcode scanner in a non-fullscreen view. 

Is there anyway to crop out the center of the camera preview to be the same size as the barcode scanner's container view?

**Comment by Rking788** [comment]
Since the default behavior is to scale the camera preview to maintain the aspect ratio and does not require any changes by the user, is it possible to merge this to provide more flexibility to users who would like to use it in a non-fullscreen view? 

Does anyone know a better way to embed the camera view in a smaller view that does not hurt performance?

**Comment by dm77** [comment]
@Rking788 Could the same functionality be achieved by overlaying elements on top the scanner view like my example code in #8 . That way you can ensure screen has other views like actionbar (toolbar), buttons, etc.

**Comment by Rking788** [comment]
It makes it difficult to adjust the viewfinder properly doing it that way especially with different screen sizes/resolutions and if the top and bottom views don't have equal heights.

If there is not enough interest in this optional feature i can just maintain my own custom fork.

**Comment by ketanpatel25** [comment]
Hi @dm77 


public ZBarScannerView(Context context, boolean stretchCameraToFill)
public ZXingScannerView(Context context, boolean stretchCameraToFill)

to use the XML layout attributes add the following namespace to the root layout:

xmlns:scanner="http://schemas.android.com/apk/res-auto"

and add this attribute to the scanner view:

scanner:stretchCameraToFill="true"

this code not working 

https://github.com/dm77/barcodescanner/issues/67

dependencies {
      compile 'com.android.support:appcompat-v7:23.1.1'
       compile 'me.dm7.barcodescanner:zxing:1.8.4'
       compile 'com.android.support:design:23.1.1'
}

**Comment by Rking788** [comment]
@ketanpatel25 this pull request was never merged in because stretching the camera preview can cause performance issues and make it hard to scan codes. So the stretch to fill attributes will not work.

This pull request should probably be closed.

**Comment by dm77** [comment]
Thank you @Rking788. PR #219 looks promising

**Comment by dm77** [comment]
Closing in favor of #219

**Pull request closed without merging**
