### PR TITLE
Add support for specifying camera by ID and fix bug when barcode scanner does not take up the whole screen.

### PR DESCRIPTION
**Pull request by mbergou**

### CODE REVIEW

**Comment by yoavst** [comment]
@dm77 why doesn't it get merged?

**Comment by stephenruda** [comment]
This solved a lot of my problems, thanks!

**Comment by Scarfoo** [comment]
@dm77 Could you please merge this request ? The scanner is working for whole preview size now, not just for a rectangle.

**Comment by dm77** [comment]
@Scarfoo @mbergou Sorry for the delay. I merged one of the commits. Working on the other one as we speak. Please give me one more day and I will push an update to maven. Thanks for your patience.

**Comment by dm77** [comment]
@mbergou thanks so much for the pull request and sorry it was ignored till today :(

**Comment by Scarfoo** [comment]
@dm77 Thank you, appreciate it :)
Great integration btw

**Pull request merged**
