### PR TITLE
Fix camera orientation detection bug

### LINKED ISSUE #172: Preview front camera upside down
Hi, please can you help me, when I try the library in front camera, I have this result ! 

device-2016-02-10-202207

### PR DESCRIPTION
**Pull request by thadcodes**
Fix inverted camera in devices with differently oriented back and forward facing cameras.  Should fix #172

### CODE REVIEW

**Comment by unip1801** [comment]
@dm77  can you please review and accept this pull request? It would be awesome to be able to use the front-facing camera without having the image in the wrong orientation! thx :)

**Comment by dm77** [comment]
@thadcodes Thank you so much for the pull request. @unip1801 Yes I am working on it. Will have it merged in this weekend.

**Comment by dm77** [comment]
Thank you @thadcodes. Merged this in.

**Comment by thadcodes** [comment]
Thanks @dm77 happy to help

**Pull request closed without merging**
