### PR TITLE
Add ability to set square viewfinder

### PR DESCRIPTION
**Pull request by squeeish**
I use this library only for scanning QR codes. Having a square viewfinder makes it look nicer.

### CODE REVIEW

**Comment by hohl** [comment]
Vote for this! :+1:

**Comment by jmuthad** [comment]
you can actually change this without a library change using the changes from #80

**Comment by squeeish** [comment]
@jmuthad which changes specifically?

**Comment by jmuthad** [comment]
@squeeish If you look at the changes you will see the code added a method that would allow you to extend the scanner view and change out the normal ViewFinderView for one you extended and then if you look at that code you will see you can change the height and width in a way that would allow you to shrink and/or stretch it to make it square.  Or you could write your own view finder and just implement the IViewFinder interface.  All this without changing the library yourself

**Comment by Rexee** [comment]
@jmuthad ViewFinderView have private access of "**findDesiredDimensionInRange**" and "**mFramingRect**". Basically you should totally copy all this class to change one single thing. I dont think that it's good idea if you only need to make square viewfinder.
Moreover, I dont understand why it's not square by default?

**Comment by dm77** [comment]
Thank you for this @squeeish. I tested it out and decided to make the squared viewfinder default as well.

**Comment by squeeish** [comment]
Awesome! I can go ahead and close this?

**Comment by dm77** [comment]
@squeeish Yes we can close this. I have decided to revert back to the setter method approach you originally. Thank you again.

**Pull request closed without merging**
